# Generated by Django 5.1.5 on 2026-02-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noutbuks', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noutbuk',
            options={'ordering': ['link', 'nalichiye', 'description', 'img', '-price'], 'verbose_name': 'Ноутбук', 'verbose_name_plural': 'Ноутбуки'},
        ),
        migrations.AlterField(
            model_name='noutbuk',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
    ]
